language: python
python:
  - '2.6.9'
  - '2.7'
install:
  - pip install -e .
    # python-coveralls requires coverage 3.
    # See https://github.com/z4r/python-coveralls/pull/41
  - pip install coverage==3.7.1
  - pip install -r requirements.txt
script:
  - cd jusibe
  - python test.py
after_success:
  - coveralls